### ISSUE TITLE
How to call back body?

### ISSUE THREAD

**Issue by DusanMilko** [welldan97/assemble-jade#5]
How do I get the body content to display?

= contents 

doesnt work

**Comment by welldan97** [comment]
I try to switch from assemble, lats time I was doing like this though:

``` jade
.col-md-offset-2.col-md-8
      {{> body }}
```

https://github.com/welldan97/welldan97.com/blob/master/source/layouts/blog.jade

**Comment by DusanMilko** [comment]
thanks
