### ISSUE TITLE
Helper

### ISSUE THREAD

**Issue by DusanMilko** [welldan97/assemble-jade#6]
What is the syntax to call a helper?

When I try something like:
!= lowercase('HELLO')

I get
Warning: lowercase is not a function

**Comment by DusanMilko** [comment]
just calling lowercase('HELLO') also doesnt work

**Comment by welldan97** [comment]
Hey @DusanMilko, sorry for late reply, I've been busy with some work. Syntax seem to be right. Might be the case that there is no such helper(`lowercase`) in the project.

Anyways, this problem seem to be not related to assemble **jade** itself, so I close the issue.
